version: '3'

services:
  postgres:
  image: postgres:15.3-alpine3.18
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - "5432:5432"

  core:
    build:
      target: production
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: always
    network_mode: "host"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: "host"
    restart: unless-stopped

volumes:
  prometheus-data: {}
  grafana-data: {}
  pgadmin: {}
